/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PotluckRouteImport } from './routes/potluck'
import { Route as JukeboxRouteImport } from './routes/jukebox'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemberIndexRouteImport } from './routes/member/index'
import { Route as MemberSigninRouteImport } from './routes/member/signin'
import { Route as InsightsSlugRouteImport } from './routes/insights/$slug'
import { Route as FeedbackSlugRouteImport } from './routes/feedback/$slug'
import { Route as AuthenticatedStewardsRouteImport } from './routes/_authenticated/stewards'
import { Route as LovableEmailEventsRouteImport } from './routes/lovable/email/events'
import { Route as ApiPublicSpotifyDiagRouteImport } from './routes/api/public/spotify-diag'
import { Route as ApiPublicSpotifyConnectRouteImport } from './routes/api/public/spotify-connect'
import { Route as ApiPublicEventFeedbackSummaryRouteImport } from './routes/api/public/event-feedback-summary'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PotluckRoute = PotluckRouteImport.update({
  id: '/potluck',
  path: '/potluck',
  getParentRoute: () => rootRouteImport,
} as any)
const JukeboxRoute = JukeboxRouteImport.update({
  id: '/jukebox',
  path: '/jukebox',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberIndexRoute = MemberIndexRouteImport.update({
  id: '/member/',
  path: '/member/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberSigninRoute = MemberSigninRouteImport.update({
  id: '/member/signin',
  path: '/member/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackSlugRoute = FeedbackSlugRouteImport.update({
  id: '/feedback/$slug',
  path: '/feedback/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStewardsRoute = AuthenticatedStewardsRouteImport.update({
  id: '/stewards',
  path: '/stewards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailEventsRoute = LovableEmailEventsRouteImport.update({
  id: '/lovable/email/events',
  path: '/lovable/email/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSpotifyDiagRoute = ApiPublicSpotifyDiagRouteImport.update({
  id: '/api/public/spotify-diag',
  path: '/api/public/spotify-diag',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSpotifyConnectRoute = ApiPublicSpotifyConnectRouteImport.update({
  id: '/api/public/spotify-connect',
  path: '/api/public/spotify-connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEventFeedbackSummaryRoute =
  ApiPublicEventFeedbackSummaryRouteImport.update({
    id: '/api/public/event-feedback-summary',
    path: '/api/public/event-feedback-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/join': typeof JoinRoute
  '/jukebox': typeof JukeboxRoute
  '/potluck': typeof PotluckRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/stewards': typeof AuthenticatedStewardsRoute
  '/feedback/$slug': typeof FeedbackSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/member/signin': typeof MemberSigninRoute
  '/member/': typeof MemberIndexRoute
  '/api/public/event-feedback-summary': typeof ApiPublicEventFeedbackSummaryRoute
  '/api/public/spotify-connect': typeof ApiPublicSpotifyConnectRoute
  '/api/public/spotify-diag': typeof ApiPublicSpotifyDiagRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/join': typeof JoinRoute
  '/jukebox': typeof JukeboxRoute
  '/potluck': typeof PotluckRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/stewards': typeof AuthenticatedStewardsRoute
  '/feedback/$slug': typeof FeedbackSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/member/signin': typeof MemberSigninRoute
  '/member': typeof MemberIndexRoute
  '/api/public/event-feedback-summary': typeof ApiPublicEventFeedbackSummaryRoute
  '/api/public/spotify-connect': typeof ApiPublicSpotifyConnectRoute
  '/api/public/spotify-diag': typeof ApiPublicSpotifyDiagRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/join': typeof JoinRoute
  '/jukebox': typeof JukeboxRoute
  '/potluck': typeof PotluckRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/stewards': typeof AuthenticatedStewardsRoute
  '/feedback/$slug': typeof FeedbackSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/member/signin': typeof MemberSigninRoute
  '/member/': typeof MemberIndexRoute
  '/api/public/event-feedback-summary': typeof ApiPublicEventFeedbackSummaryRoute
  '/api/public/spotify-connect': typeof ApiPublicSpotifyConnectRoute
  '/api/public/spotify-diag': typeof ApiPublicSpotifyDiagRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/join'
    | '/jukebox'
    | '/potluck'
    | '/privacy'
    | '/reset-password'
    | '/stewards'
    | '/feedback/$slug'
    | '/insights/$slug'
    | '/member/signin'
    | '/member/'
    | '/api/public/event-feedback-summary'
    | '/api/public/spotify-connect'
    | '/api/public/spotify-diag'
    | '/lovable/email/events'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/join'
    | '/jukebox'
    | '/potluck'
    | '/privacy'
    | '/reset-password'
    | '/stewards'
    | '/feedback/$slug'
    | '/insights/$slug'
    | '/member/signin'
    | '/member'
    | '/api/public/event-feedback-summary'
    | '/api/public/spotify-connect'
    | '/api/public/spotify-diag'
    | '/lovable/email/events'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contact'
    | '/join'
    | '/jukebox'
    | '/potluck'
    | '/privacy'
    | '/reset-password'
    | '/_authenticated/stewards'
    | '/feedback/$slug'
    | '/insights/$slug'
    | '/member/signin'
    | '/member/'
    | '/api/public/event-feedback-summary'
    | '/api/public/spotify-connect'
    | '/api/public/spotify-diag'
    | '/lovable/email/events'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  JoinRoute: typeof JoinRoute
  JukeboxRoute: typeof JukeboxRoute
  PotluckRoute: typeof PotluckRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  FeedbackSlugRoute: typeof FeedbackSlugRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  MemberSigninRoute: typeof MemberSigninRoute
  MemberIndexRoute: typeof MemberIndexRoute
  ApiPublicEventFeedbackSummaryRoute: typeof ApiPublicEventFeedbackSummaryRoute
  ApiPublicSpotifyConnectRoute: typeof ApiPublicSpotifyConnectRoute
  ApiPublicSpotifyDiagRoute: typeof ApiPublicSpotifyDiagRoute
  LovableEmailEventsRoute: typeof LovableEmailEventsRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/potluck': {
      id: '/potluck'
      path: '/potluck'
      fullPath: '/potluck'
      preLoaderRoute: typeof PotluckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jukebox': {
      id: '/jukebox'
      path: '/jukebox'
      fullPath: '/jukebox'
      preLoaderRoute: typeof JukeboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/': {
      id: '/member/'
      path: '/member'
      fullPath: '/member/'
      preLoaderRoute: typeof MemberIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/signin': {
      id: '/member/signin'
      path: '/member/signin'
      fullPath: '/member/signin'
      preLoaderRoute: typeof MemberSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/$slug': {
      id: '/feedback/$slug'
      path: '/feedback/$slug'
      fullPath: '/feedback/$slug'
      preLoaderRoute: typeof FeedbackSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stewards': {
      id: '/_authenticated/stewards'
      path: '/stewards'
      fullPath: '/stewards'
      preLoaderRoute: typeof AuthenticatedStewardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/events': {
      id: '/lovable/email/events'
      path: '/lovable/email/events'
      fullPath: '/lovable/email/events'
      preLoaderRoute: typeof LovableEmailEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/spotify-diag': {
      id: '/api/public/spotify-diag'
      path: '/api/public/spotify-diag'
      fullPath: '/api/public/spotify-diag'
      preLoaderRoute: typeof ApiPublicSpotifyDiagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/spotify-connect': {
      id: '/api/public/spotify-connect'
      path: '/api/public/spotify-connect'
      fullPath: '/api/public/spotify-connect'
      preLoaderRoute: typeof ApiPublicSpotifyConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/event-feedback-summary': {
      id: '/api/public/event-feedback-summary'
      path: '/api/public/event-feedback-summary'
      fullPath: '/api/public/event-feedback-summary'
      preLoaderRoute: typeof ApiPublicEventFeedbackSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedStewardsRoute: typeof AuthenticatedStewardsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedStewardsRoute: AuthenticatedStewardsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  JoinRoute: JoinRoute,
  JukeboxRoute: JukeboxRoute,
  PotluckRoute: PotluckRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  FeedbackSlugRoute: FeedbackSlugRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  MemberSigninRoute: MemberSigninRoute,
  MemberIndexRoute: MemberIndexRoute,
  ApiPublicEventFeedbackSummaryRoute: ApiPublicEventFeedbackSummaryRoute,
  ApiPublicSpotifyConnectRoute: ApiPublicSpotifyConnectRoute,
  ApiPublicSpotifyDiagRoute: ApiPublicSpotifyDiagRoute,
  LovableEmailEventsRoute: LovableEmailEventsRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
